# Generated by Django 4.2.9 on 2024-03-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['placeId'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
