# Generated by Django 4.2.9 on 2024-04-03 18:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_description_long_place_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
