# Generated by Django 4.2.9 on 2024-03-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['description_short'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
