# Generated by Django 4.2.9 on 2024-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='upload',
            new_name='image',
        ),
    ]
