# Generated by Django 4.2.9 on 2024-04-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_upload_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
