# Generated by Django 4.2.9 on 2024-04-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_photo_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id'], 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
    ]
